version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    command: ["./entrypoint.sh"]
    ports:
      - "8080:8080"
    volumes:
      - ./migrations:/app/migrations

volumes:
  pgdata:
