// Code generated by generator, DO NOT EDIT.
package token

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// CreateToken inserts a new Token into the database.
func (r *CommandRepository) Create(ctx context.Context, model *Token) error {
	var query string
	var args []any

	switch r.placeholder {
	case DollarWildcard:
		query, args = sq.Insert(TableToken).Columns(ColumnTokenUserGuid, ColumnTokenRefreshToken, ColumnTokenActive, ColumnTokenUserAgent, ColumnTokenIP).Values(model.UserGuid, model.RefreshToken, model.Active, model.UserAgent, model.IP).PlaceholderFormat(sq.Dollar).MustSql()
	default:
		query, args = sq.Insert(TableToken).Columns(ColumnTokenUserGuid, ColumnTokenRefreshToken, ColumnTokenActive, ColumnTokenUserAgent, ColumnTokenIP).Values(model.UserGuid, model.RefreshToken, model.Active, model.UserAgent, model.IP).PlaceholderFormat(sq.Question).MustSql()
	}

	if _, err := r.runner.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}

// CreateToken inserts a new Token into the database.
func (r *CommandRepository) CreateMany(ctx context.Context, tokens []Token) error {
	var builder sq.InsertBuilder

	switch r.placeholder {
	case DollarWildcard:
		builder = sq.Insert(TableToken).Columns(ColumnTokenUserGuid, ColumnTokenRefreshToken, ColumnTokenActive, ColumnTokenUserAgent, ColumnTokenIP).PlaceholderFormat(sq.Dollar)
	default:
		builder = sq.Insert(TableToken).Columns(ColumnTokenUserGuid, ColumnTokenRefreshToken, ColumnTokenActive, ColumnTokenUserAgent, ColumnTokenIP).PlaceholderFormat(sq.Question)
	}

	for _, model := range tokens {
		builder = builder.Values(model.UserGuid, model.RefreshToken, model.Active, model.UserAgent, model.IP)
	}
	query, args := builder.MustSql()

	if _, err := r.runner.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}
