// Code generated by generator, DO NOT EDIT.
package token

import (
	"iter"
	"reflect"
	"slices"
	"sort"
)

type Tokens []Token

func (s Tokens) ToIDs() []int64 {
	output := make([]int64, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].ID)
	}
	return output
}
func (s Tokens) ToUserGuids() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].UserGuid)
	}
	return output
}
func (s Tokens) ToRefreshTokens() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].RefreshToken)
	}
	return output
}
func (s Tokens) ToActives() []bool {
	output := make([]bool, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Active)
	}
	return output
}
func (s Tokens) ToUserAgents() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].UserAgent)
	}
	return output
}
func (s Tokens) ToIPs() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].IP)
	}
	return output
}
func (s Tokens) FindByID(finder int64) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].ID == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) FindByUserGuid(finder string) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].UserGuid == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) FindByRefreshToken(finder string) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].RefreshToken == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) FindByActive(finder bool) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Active == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) FindByUserAgent(finder string) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].UserAgent == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) FindByIP(finder string) (Token, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].IP == finder {
			return s[i], true
		}
	}
	return Token{}, false
}
func (s Tokens) SortByID(asc bool) Tokens {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].ID < s[j].ID
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].ID > s[j].ID
	})
	return s
}
func (s Tokens) SortByUserGuid(asc bool) Tokens {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].UserGuid < s[j].UserGuid
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].UserGuid > s[j].UserGuid
	})
	return s
}
func (s Tokens) SortByRefreshToken(asc bool) Tokens {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].RefreshToken < s[j].RefreshToken
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].RefreshToken > s[j].RefreshToken
	})
	return s
}
func (s Tokens) SortByUserAgent(asc bool) Tokens {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].UserAgent < s[j].UserAgent
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].UserAgent > s[j].UserAgent
	})
	return s
}
func (s Tokens) SortByIP(asc bool) Tokens {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].IP < s[j].IP
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].IP > s[j].IP
	})
	return s
}

func (s Tokens) FilterFunc(f func(i Token) bool) Tokens {
	output := make(Tokens, 0, len(s))
	for i := 0; i < len(s); i++ {
		if f(s[i]) {
			output = append(output, s[i])
		}
	}
	return output
}
func (s Tokens) GetFirstID() (*int64, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].ID, true
}
func (s Tokens) GetFirstUserGuid() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].UserGuid, true
}
func (s Tokens) GetFirstRefreshToken() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].RefreshToken, true
}
func (s Tokens) GetFirstActive() (*bool, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Active, true
}
func (s Tokens) GetFirstUserAgent() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].UserAgent, true
}
func (s Tokens) GetFirstIP() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].IP, true
}

func (s Tokens) GetFirst() (Token, bool) {
	if len(s) < 1 {
		return Token{}, false
	}
	return s[0], true
}

func (s Tokens) All() iterToken {
	return func(yield func(Token) bool) {
		for _, elem := range s {
			if !yield(elem) {
				return
			}
		}
	}
}

// Iterators
type iterToken iter.Seq[Token]

func (i iterToken) FilterFunc(predicate func(Token) bool) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if predicate(elem) && !yield(elem) {
				return
			}
		}
	}
}

func (i iterToken) Map(transform func(Token) Token) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if !yield(transform(elem)) {
				return
			}
		}
	}
}

func (i iterToken) Take(n int) iterToken {
	count := 0
	return func(yield func(Token) bool) {
		for elem := range i {
			if count >= n || !yield(elem) {
				return
			}
			count++
		}
	}
}

func (i iterToken) Find(findFunc func(Token) bool) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if findFunc(elem) && !yield(elem) {
				return
			}
		}
	}
}

// doesnot work with pointers
func (i iterToken) Distinct(keyFunc func(Token) any) iterToken {
	seen := make(map[any]bool)
	return func(yield func(Token) bool) {
		for elem := range i {
			key := keyFunc(elem)
			if key != nil {
				val := reflect.ValueOf(key)
				switch val.Kind() {
				case reflect.Ptr, reflect.Interface,
					reflect.Slice, reflect.Map,
					reflect.Chan, reflect.Func:
					if val.IsNil() {
						continue
					}
				}
			}
			if !seen[key] {
				seen[key] = true
				if !yield(elem) {
					return
				}
			}
		}
	}
}
func (i iterToken) FilterByID(id int64) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if id == elem.ID && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) FilterByUserGuid(userguid string) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if userguid == elem.UserGuid && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) FilterByRefreshToken(refreshtoken string) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if refreshtoken == elem.RefreshToken && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) FilterByActive(active bool) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if active == elem.Active && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) FilterByUserAgent(useragent string) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if useragent == elem.UserAgent && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) FilterByIP(ip string) iterToken {
	return func(yield func(Token) bool) {
		for elem := range i {
			if ip == elem.IP && !yield(elem) {
				return
			}
		}
	}
}
func (i iterToken) ToIDs() int64Iter {
	return func(yield func(int64) bool) {
		for elem := range i {
			if !yield(elem.ID) {
				return
			}
		}
	}
}
func (i iterToken) ToUserGuids() iter.Seq[string] {
	return func(yield func(string) bool) {
		for elem := range i {
			if !yield(elem.UserGuid) {
				return
			}
		}
	}
}
func (i iterToken) ToRefreshTokens() iter.Seq[string] {
	return func(yield func(string) bool) {
		for elem := range i {
			if !yield(elem.RefreshToken) {
				return
			}
		}
	}
}
func (i iterToken) ToActives() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for elem := range i {
			if !yield(elem.Active) {
				return
			}
		}
	}
}
func (i iterToken) ToUserAgents() iter.Seq[string] {
	return func(yield func(string) bool) {
		for elem := range i {
			if !yield(elem.UserAgent) {
				return
			}
		}
	}
}
func (i iterToken) ToIPs() iter.Seq[string] {
	return func(yield func(string) bool) {
		for elem := range i {
			if !yield(elem.IP) {
				return
			}
		}
	}
}

func (i iterToken) First() (Token, bool) {
	for elem := range i {
		return elem, true
	}
	return Token{}, false
}

func (i iterToken) ForEach(f func(Token)) {
	for elem := range i {
		f(elem)
	}
}

func (i iterToken) Collect() []Token {
	return slices.Collect(iter.Seq[Token](i))
}

// -1 if x is less than y,
//
//	0 if x equals y,
//
// +1 if x is greater than y.
func (i iterToken) Sort(sortFunc func(x, y Token) int) []Token {
	return slices.SortedFunc(iter.Seq[Token](i), sortFunc)
}

type intIter iter.Seq[int]
type int8Iter iter.Seq[int8]
type int16Iter iter.Seq[int16]
type int32Iter iter.Seq[int32]
type int64Iter iter.Seq[int64]
type uintIter iter.Seq[uint]
type uint8Iter iter.Seq[uint8]
type uint16Iter iter.Seq[uint16]
type uint32Iter iter.Seq[uint32]
type uint64Iter iter.Seq[uint64]
type uintptrIter iter.Seq[uintptr]
type float32Iter iter.Seq[float32]
type float64Iter iter.Seq[float64]

func (i intIter) Sum() int {
	var res int
	for elem := range i {
		res += elem
	}
	return res
}
func (i intIter) Min() int {
	var min int
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i intIter) Max() int {
	var max int
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i intIter) Average() int {
	var sum, count int
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i int8Iter) Sum() int8 {
	var res int8
	for elem := range i {
		res += elem
	}
	return res
}
func (i int8Iter) Min() int8 {
	var min int8
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i int8Iter) Max() int8 {
	var max int8
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i int8Iter) Average() int8 {
	var sum, count int8
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i int16Iter) Sum() int16 {
	var res int16
	for elem := range i {
		res += elem
	}
	return res
}
func (i int16Iter) Min() int16 {
	var min int16
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i int16Iter) Max() int16 {
	var max int16
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i int16Iter) Average() int16 {
	var sum, count int16
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i int32Iter) Sum() int32 {
	var res int32
	for elem := range i {
		res += elem
	}
	return res
}
func (i int32Iter) Min() int32 {
	var min int32
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i int32Iter) Max() int32 {
	var max int32
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i int32Iter) Average() int32 {
	var sum, count int32
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i int64Iter) Sum() int64 {
	var res int64
	for elem := range i {
		res += elem
	}
	return res
}
func (i int64Iter) Min() int64 {
	var min int64
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i int64Iter) Max() int64 {
	var max int64
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i int64Iter) Average() int64 {
	var sum, count int64
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uintIter) Sum() uint {
	var res uint
	for elem := range i {
		res += elem
	}
	return res
}
func (i uintIter) Min() uint {
	var min uint
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uintIter) Max() uint {
	var max uint
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uintIter) Average() uint {
	var sum, count uint
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uint8Iter) Sum() uint8 {
	var res uint8
	for elem := range i {
		res += elem
	}
	return res
}
func (i uint8Iter) Min() uint8 {
	var min uint8
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uint8Iter) Max() uint8 {
	var max uint8
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uint8Iter) Average() uint8 {
	var sum, count uint8
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uint16Iter) Sum() uint16 {
	var res uint16
	for elem := range i {
		res += elem
	}
	return res
}
func (i uint16Iter) Min() uint16 {
	var min uint16
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uint16Iter) Max() uint16 {
	var max uint16
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uint16Iter) Average() uint16 {
	var sum, count uint16
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uint32Iter) Sum() uint32 {
	var res uint32
	for elem := range i {
		res += elem
	}
	return res
}
func (i uint32Iter) Min() uint32 {
	var min uint32
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uint32Iter) Max() uint32 {
	var max uint32
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uint32Iter) Average() uint32 {
	var sum, count uint32
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uint64Iter) Sum() uint64 {
	var res uint64
	for elem := range i {
		res += elem
	}
	return res
}
func (i uint64Iter) Min() uint64 {
	var min uint64
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uint64Iter) Max() uint64 {
	var max uint64
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uint64Iter) Average() uint64 {
	var sum, count uint64
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i uintptrIter) Sum() uintptr {
	var res uintptr
	for elem := range i {
		res += elem
	}
	return res
}
func (i uintptrIter) Min() uintptr {
	var min uintptr
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i uintptrIter) Max() uintptr {
	var max uintptr
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i uintptrIter) Average() uintptr {
	var sum, count uintptr
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i float32Iter) Sum() float32 {
	var res float32
	for elem := range i {
		res += elem
	}
	return res
}
func (i float32Iter) Min() float32 {
	var min float32
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i float32Iter) Max() float32 {
	var max float32
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i float32Iter) Average() float32 {
	var sum, count float32
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
func (i float64Iter) Sum() float64 {
	var res float64
	for elem := range i {
		res += elem
	}
	return res
}
func (i float64Iter) Min() float64 {
	var min float64
	first := true
	for elem := range i {
		if first || elem < min {
			min = elem
			first = false
		}
	}
	return min
}
func (i float64Iter) Max() float64 {
	var max float64
	first := true
	for elem := range i {
		if first || elem > max {
			max = elem
			first = false
		}
	}
	return max
}
func (i float64Iter) Average() float64 {
	var sum, count float64
	for elem := range i {
		sum += elem
		count++
	}
	if count == 0 {
		return 0
	}
	return sum / count
}
