// Code generated by generator, DO NOT EDIT.
package token

const (
	TableToken              = "tokens"
	ColumnTokenID           = "id"
	ColumnTokenUserGuid     = "user_guid"
	ColumnTokenRefreshToken = "refresh_token"
	ColumnTokenActive       = "active"
	ColumnTokenUserAgent    = "user_agent"
	ColumnTokenIP           = "ip"
)
