// Code generated by generator, DO NOT EDIT.
package blacklist

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// DeleteBlacklist deletes a Blacklist by ID.
func (r *CommandRepository) Delete(ctx context.Context, opts ...FilterOpt) error {
	var b sq.DeleteBuilder
	switch r.placeholder {
	case DollarWildcard:
		b = sq.Delete(TableBlacklist).PlaceholderFormat(sq.Dollar)
	default:
		b = sq.Delete(TableBlacklist).PlaceholderFormat(sq.Question)
	}

	f := Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](&f)
	}
	b = applyWhere(b, &f)
	query, args := b.MustSql()
	if _, err := r.runner.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec delete query %s with args %v error = %w", query, args, err)
	}
	return nil
}
